name: srna
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - intarna=3.4.1
  - viennarna
  - boost
  - pandas
  - numpy
  - scikit-learn
  - fastapi
  - uvicorn
  - streamlit
  - requests
  - matplotlib
